# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fca63df272000cd43c9f9398339ba5a60709d7b2bdfe56fbb74c42d86388061f27bf14871e21530f5eb0536a4491a3adea42eea6cbcf88ff0be7cdabe33a6af7

test:
  secret_key_base: 352c103511560d94a8cd23a1c4000954abca8438bbf585e265570e4139b1214fe934d8156a5edbfb3c8f28c3e99eec199f32d70d8203b0cfa12217ff06fed076

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
